{{- if not .Values.linkwarden.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkwarden.fullname" . }}-env-secrets
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Auth Settings
  NEXTAUTH_URL: "{{ .Values.linkwarden.nextAuthUrl }}"
  NEXTAUTH_SECRET: "{{ .Values.linkwarden.nextAuthSecret }}"
  # AWS S3 Settings
  {{- if eq .Values.linkwarden.storage.type "s3" -}}
  SPACES_KEY: "{{ .Values.linkwarden.storage.s3.accessKey }}"
  SPACES_SECRET: "{{ .Values.linkwarden.storage.s3.secretKey }}"
  SPACES_ENDPOINT: "{{ .Values.linkwarden.storage.s3.endpoint }}"
  SPACES_BUCKET_NAME: "{{ .Values.linkwarden.storage.s3.bucketName }}"
  SPACES_REGION: "{{ .Values.linkwarden.storage.s3.region }}"
  SPACES_FORCE_PATH_STYLE: "{{ .Values.linkwarden.storage.s3.forcePathStyle }}"
  {{- end }}
  {{/* If using integrated cnpg postgres, then database url will be set in deployment from the cnpg secret */}}
  {{- if .Values.linkwarden.externalDatabaseUri }}
  DATABASE_URL: "{{ .Values.linkwarden.externalDatabaseUri }}"
  {{- end }}
  # SMTP Settings
  {{- if .Values.linkwarden.emailProvider }}
  NEXT_PUBLIC_EMAIL_PROVIDER: "{{ .Values.linkwarden.smtp.emailProvider }}"
  EMAIL_FROM: "{{ .Values.linkwarden.smtp.emailFrom }}"
  EMAIL_SERVER: "{{ .Values.linkwarden.smtp.emailServer }}"
  BASE_URL: "{{ .Values.linkwarden.smtp.baseUrl }}"
  {{- end }}
  # Playwright browser proxy settings
  {{- if .Values.linkwarden.browser.proxyUrl }}
  PROXY: "{{ .Values.linkwarden.browser.proxyUrl }}"
  PROXY_USERNAME: "{{ .Values.linkwarden.browser.proxyUsername }}"
  PROXY_PASSWORD: "{{ .Values.linkwarden.browser.proxyPassword }}"
  PROXY_BYPASS: "localhost,127.0.0.1"
  {{- end }}
  # Meili search configuratiuon
  {{- if .Values.linkwarden.meili.url }}
  MEILI_HOST: "{{ .Values.linkwarden.meili.url }}"
  MEILI_MASTER_KEY: "{{ .Values.linkwarden.meili.masterkey }}"
  MEILI_TIMEOUT: "{{ .Values.linkwarden.meili.timeout }}"
  {{- end }}

{{- end }}
